services:
    database:
      container_name: budgetcontrol-db
      image: postgres:13.18
      restart: unless-stopped
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
      volumes:
        - db_persistent:/var/lib/mysql
      networks:
        - budgetcontrol_network

    cache:
      container_name: budgetcontrol-redis
      image: redis:7.2-rc2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
      volumes:
        - cache:/data
      networks:
        - budgetcontrol_network
        
volumes:
  db_persistent:
    name: budgetcontrol_core_database
    external: false
  cache:
    name: budgetcontrol_core_cache
    external: false

networks:
  budgetcontrol_network:
    external: false
    name: budgetcontrol_network
