services:

  core:
    container_name: budgetcontrol-core
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Core/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  proxy:
    platform: linux/x86_64
    container_name: budgetcontrol-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx/conf.d/:/etc/nginx/conf.d/
      - ./bin/certbot/conf:/etc/letsencrypt
      - ./bin/certbot/www:/var/www/certbot
    networks:
      - budgetcontrol_network
    depends_on:
      - core
      
  ms-stats:
    container_name: budgetcontrol-ms-stats
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Stats/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped
  
  ms-workspace:
    container_name: budgetcontrol-ms-workspace
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Workspace/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped
  
  gateway:
    container_name: budgetcontrol-gateway
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Gateway/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-authentication:
    container_name: budgetcontrol-ms-authentication
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Authentication/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-jobs:
    container_name: budgetcontrol-ms-jobs
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/CommandJobs/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-budget:
    container_name: budgetcontrol-ms-budget
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Budget/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-entries:
    container_name: budgetcontrol-ms-entries
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Entries/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-wallets:
    container_name: budgetcontrol-ms-wallets
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Wallets/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-searchengine:
    container_name: budgetcontrol-ms-searchengine
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/SearchEngine/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-labels:
    container_name: budgetcontrol-ms-labels
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Labels/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-debt:
    container_name: budgetcontrol-ms-debt
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Debt/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-savings:
    container_name: budgetcontrol-ms-savings
    image: mlabfactory/php8-apache:${DOCKER_TAG}
    volumes:
      - ./microservices/Debt/:/var/www/workdir
    networks:
      - budgetcontrol_network
    restart: unless-stopped

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
