version: '2.2'

services:
    database:
      container_name: budgetcontrol-db
      image: mysql:5.7
      restart: unless-stopped
      ports:
        - "3336:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      volumes:
        - mysql_persistent:/var/lib/mysql
      networks:
        - budgetcontrol_network

    cache:
      container_name: budgetcontrol-redis
      image: redis:7.2-rc2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_REDIS_PASSWORD}
      volumes:
        - cache:/data
      networks:
        - budgetcontrol_network
        
volumes:
  mysql_persistent:
    name: budgetcontrol_core_database
    external: false
  cache:
    name: budgetcontrol_core_cache
    external: false

networks:
  budgetcontrol_network:
    external: false
    name: budgetcontrol_network
