services:

  core:
    container_name: budgetcontrol-core
    image: budgetcontrol316/core:main
    networks:
      - budgetcontrol_network

  proxy:
    container_name: budgetcontrol-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - budgetcontrol_network
      
  ms-stats:
    container_name: budgetcontrol-ms-stats
    image: budgetcontrol316/stats:v1.3.1
    networks:
      - budgetcontrol_network
    restart: unless-stopped
  
  ms-workspace:
    container_name: budgetcontrol-ms-workspace
    image: budgetcontrol316/workspace:v1.1.8
    networks:
      - budgetcontrol_network
    restart: unless-stopped
  
  gateway:
    container_name: budgetcontrol-gateway
    image: budgetcontrol316/gateway:main
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-authentication:
    container_name: budgetcontrol-ms-authentication
    image: budgetcontrol316/authentication:v1.3.2
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-jobs:
    container_name: budgetcontrol-ms-jobs
    image: budgetcontrol316/jobs:v1.3.4
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-budget:
    container_name: budgetcontrol-ms-budget
    image: budgetcontrol316/budget:v1.1.3
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-entries:
    container_name: budgetcontrol-ms-entries
    image: budgetcontrol316/entries:v1.0.7
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-wallets:
    container_name: budgetcontrol-ms-wallets
    image: budgetcontrol316/wallets:v1.2.1
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-searchengine:
    container_name: budgetcontrol-ms-searchengine
    image: budgetcontrol316/searchengine:v1.0.1
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-labels:
    container_name: budgetcontrol-ms-labels
    image: budgetcontrol316/labels:main
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  ms-debt:
    container_name: budgetcontrol-ms-debt
    image: budgetcontrol316/bebt:v1.1.1
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  pwa:
    container_name: budgetcontrol-pwa
    image: budgetcontrol316/pwa:v3.1.1
    networks:
      - budgetcontrol_network
    restart: unless-stopped

networks:
  budgetcontrol_network:
    name: budgetcontrol_network
