version: '3'

services:
    proxy:
      volumes:
        - ./bin/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
        - ./bin/certbot/conf:/etc/letsencrypt
        - ./bin/certbot/www:/var/www/certbot

    ms-stats:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8084:80"
    
    ms-workspace:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8082:80"
    
    gateway:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8081:80"

    ms-authentication:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8083:80"
      
    ms-jobs:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug

    ms-budget:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8085:80"
      
    ms-entries:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8086:80"

    ms-wallets:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8087:80"

    ms-labels:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8088:80"

    ms-searchengine:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8089:80"

    ms-debt:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "8090:80"

    database:
      ports:
        - "3336:3306"

    core:
      image: mlabfactory/php8-apache:${DOCKER_TAG}-xdebug
      ports:
        - "3000:80"

volumes:
  mysql_persistent:
    name: budgetcontrol_core_database
    external: false
  cache:
    name: budgetcontrol_core_cache
    external: false